repository:
  default_branch: main
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: false
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - gate / all-required-green
          - Docker / build
          - Release Notes / generate
      enforce_admins: true
      required_conversation_resolution: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_review: true
        dismiss_stale_reviews: true
        require_last_push_approval: true
