"""Ensure the pinned requirements file is in sync with ``pyproject.toml``.

The test normalises both the freshly compiled output and the existing
``requirements.lock`` file so that timestamp comments or command variations do
not cause spurious failures.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest


def _normalize_lockfile_content(content: str) -> str:
    """Strip unstable comment lines and normalise the compile command.

    Skips '# via' comments entirely because uv's dependency resolution can produce
    different transitive dependency lists across Python versions, leading to
    spurious test failures when the lockfile is functionally equivalent.
    """

    lines = []

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            if re.match(r"^#.*autogenerated.*by.*", stripped, re.IGNORECASE):
                continue
            if re.match(r"^#\s*uv pip compile.*", stripped):
                lines.append("#    uv pip compile pyproject.toml -o requirements.lock")
                continue
            if re.search(r"\d{4}-\d{2}-\d{2}", stripped) or re.search(
                r"\d{2}:\d{2}", stripped
            ):
                continue

            # Skip '# via' lines in all forms:
            # - "# via" (standalone header)
            # - "#   package" (indented list item)
            # - "# via package" (single-line form)
            if (
                stripped == "# via"
                or stripped.startswith("#   ")
                or re.match(r"^#\s+via\s+\w", stripped)
            ):
                continue

            lines.append(stripped)
        else:
            lines.append(stripped)

    return "\n".join(lines) + ("\n" if lines else "")


@pytest.mark.skipif(shutil.which("uv") is None, reason="uv CLI not installed")
@pytest.mark.skipif(
    os.getenv("TREND_FORCE_DEP_LOCK_CHECK", "0") != "1",
    reason="Dependency lockfile check only runs during scheduled refresh",
)
def test_lockfile_up_to_date() -> None:
    """Compare compiled dependencies with the committed lockfile."""

    result = subprocess.run(
        ["uv", "pip", "compile", "pyproject.toml"],
        capture_output=True,
        text=True,
        check=True,
    )
    compiled = _normalize_lockfile_content(result.stdout)

    lock_path = Path("requirements.lock")
    assert lock_path.exists(), "requirements.lock file not found"
    existing = _normalize_lockfile_content(lock_path.read_text())

    assert compiled == existing, (
        "requirements.lock is out of date. Run "
        "'uv pip compile pyproject.toml -o requirements.lock' to update it."
    )


def test_normalize_lockfile_content() -> None:
    """Check that normalisation removes volatile comment lines."""

    sample = """# This file was autogenerated by uv via the following command:
#    uv pip compile pyproject.toml -o requirements-2024-01-15.lock
# Generated on 2024-01-15 14:30:22
pkg==1.0.0
    # via something
"""

    # After normalization, '# via' lines are completely removed
    expected = """#    uv pip compile pyproject.toml -o requirements.lock
pkg==1.0.0
"""

    assert _normalize_lockfile_content(sample) == expected


def test_normalize_via_comments() -> None:
    """Check that via comments are normalized across Python versions."""

    # Simulate Python 3.11 output with ipython in via list
    sample_311 = """typing-extensions==4.15.0
    # via
    #   ipython
    #   pydantic
    #   pydantic-core
"""

    # Simulate Python 3.12 output without ipython in via list
    sample_312 = """typing-extensions==4.15.0
    # via
    #   pydantic
    #   pydantic-core
"""

    # Both should normalize to the same output (skipping via comments)
    normalized_311 = _normalize_lockfile_content(sample_311)
    normalized_312 = _normalize_lockfile_content(sample_312)

    # The normalization should skip all '# via' comments
    assert normalized_311 == normalized_312
    assert "typing-extensions==4.15.0" in normalized_311
    assert "# via" not in normalized_311
    assert "#   pydantic" not in normalized_311


def test_lockfile_up_to_date_mock() -> None:
    """Smoke-test the lockfile check with mocked subprocess and filesystem."""

    mock_output = """# This file was autogenerated by uv via the following command:
#    uv pip compile pyproject.toml -o requirements.lock
pkg==1.0.0
"""

    with (
        patch("subprocess.run") as mock_run,
        patch("pathlib.Path.read_text") as mock_read,
        patch("pathlib.Path.exists") as mock_exists,
    ):
        mock_run.return_value = MagicMock(stdout=mock_output)
        mock_read.return_value = mock_output
        mock_exists.return_value = True

        # Should not raise
        test_lockfile_up_to_date()

        mock_run.assert_called_once_with(
            ["uv", "pip", "compile", "pyproject.toml"],
            capture_output=True,
            text=True,
            check=True,
        )
