name: Bug report
description: Something broke. Keep it factual.
labels: ["type:bug","codex-ready","risk:low"]
body:
  - type: input
    id: env
    attributes:
      label: Environment
      description: Python version, OS, commit hash
      placeholder: "Python 3.11, macOS 14.5, commit abc123"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Exact steps, expected vs actual behavior.
      value: |
        1.
        2.
        3.
  - type: dropdown
    id: labels
    attributes:
      label: Routing
      description: "Pick who should handle this issue. `risk:low` is added automatically."
      default: agent:codex
      options:
        - label: 🤖 Codex (default)
          value: agent:codex
        - label: 🤖 Copilot
          value: agent:copilot
        - label: 🙋 Human maintainer
          value: agent:human
    validations:
      required: true
