name: Feature request
description: Small, single-scope feature for the Streamlit app or sim layer
labels: ["type:feature","codex-ready","risk:low"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One-sentence description of the feature.
      placeholder: e.g., "Add preview of score frame before selection"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of verifiable outcomes.
      value: |
        - [ ] A
        - [ ] B
        - [ ] C
    validations:
      required: true
  - type: dropdown
    id: labels
    attributes:
      label: Routing
      description: "Pick who should handle this issue. `risk:low` is added automatically."
      default: agent:codex
      options:
        - label: 🤖 Codex (default)
          value: agent:codex
        - label: 🤖 Copilot
          value: agent:copilot
        - label: 🙋 Human maintainer
          value: agent:human
    validations:
      required: true
