name: Feature request
description: Small, single-scope feature for the Streamlit app or sim layer
labels: ["type:feature","risk:low","agent:codex","automerge","codex-ready"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One-sentence description of the feature.
      placeholder: e.g., "Add preview of score frame before selection"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of verifiable outcomes.
      value: |
        - [ ] A
        - [ ] B
        - [ ] C
    validations:
      required: true
