name: DEPRECATED Assign Issue to Codex Agent (Replaced)

# Minimal stub placeholder. Original legacy workflow removed.
# Active replacement: codex-assign-minimal.yml

on:
  workflow_dispatch:

jobs:
  stub:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Legacy workflow deprecated. Use codex-assign-minimal.yml."
