[tool.black]
extend-exclude = '(notebooks|Old|.*\.ipynb)'

[tool.ruff]
extend-exclude = ["notebooks", "Old", "*.ipynb"]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
