name: "Autofix Python Formatting"
description: "Run ruff, black, isort, docformatter with pinned versions and emit summary"
inputs:
  python-version:
    description: "Python version"
    required: false
    default: "3.12"
outputs:
  changed:
    description: "Whether any files were modified by the fixers"
    value: ${{ steps.runfix.outputs.changed }}
  remaining_issues:
    description: "Count of unresolved ruff diagnostics after autofix phase"
    value: ${{ steps.runfix.outputs.remaining_issues }}
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Load tool versions
      shell: bash
      run: |
        cat .github/workflows/autofix-versions.env >> $GITHUB_ENV
    - name: Install fixers
      shell: bash
      run: |
        python -m pip install -U pip
        pip install -e ".[dev]" \
          ruff==${RUFF_VERSION} \
          black==${BLACK_VERSION} \
          isort==${ISORT_VERSION} \
          docformatter==${DOCFORMATTER_VERSION}
    - name: Run fixers
      id: runfix
      shell: bash
      run: |
        echo "[autofix] Phase 1: applying safe fixes (ruff + isort + docformatter + black final)"
        # Ruff first (fast) – non-fatal
        ruff check --fix --exit-zero .
        # isort next so import reordering is final before black
        isort .
        # docformatter before black so black enforces final layout
        docformatter -r -i src tests || true
        # black last for canonical formatting
        black .

        echo "[autofix] Phase 2: collect remaining ruff diagnostics (non-fatal)"
        # Capture remaining issues for summary; never fail this job here
        if ! ruff check . > ruff_remaining.log 2>&1; then
          echo "[autofix] Ruff reported remaining issues (expected for non-auto-fixable codes)."
        fi
        remaining_count=$(grep -cE '^[^ ]+:[0-9]+:[0-9]+:' ruff_remaining.log || true)
        echo "remaining_issues=$remaining_count" >> $GITHUB_OUTPUT
        echo "[autofix] Remaining ruff issues: $remaining_count"

        # --- Type hygiene (lightweight) ---
        echo "[autofix] Running auto_type_hygiene..."
        if [ -f scripts/auto_type_hygiene.py ]; then
          python scripts/auto_type_hygiene.py || true
        else
          echo "(skip) scripts/auto_type_hygiene.py not found"
        fi
        echo "[autofix] Installing missing type stubs (non-fatal)..."
        mypy --install-types --non-interactive || true
        # Optional warm cache (do not fail build)
        mypy src/ --ignore-missing-imports --follow-imports=silent > /dev/null 2>&1 || true

        if ! git diff --quiet; then echo "changed=true" >> $GITHUB_OUTPUT; else echo "changed=false" >> $GITHUB_OUTPUT; fi
    - name: Summary
      shell: bash
      run: |
        echo "### Composite Autofix Summary" >> $GITHUB_STEP_SUMMARY
        echo "Changed: ${{ steps.runfix.outputs.changed }}" >> $GITHUB_STEP_SUMMARY
        echo "Remaining ruff issues: ${{ steps.runfix.outputs.remaining_issues }}" >> $GITHUB_STEP_SUMMARY
        echo "Remaining Ruff Issues: ${{ steps.runfix.outputs.remaining_issues }}" >> $GITHUB_STEP_SUMMARY