name: "Autofix Python Formatting"
description: "Run ruff, black, isort, docformatter with pinned versions and emit summary"
inputs:
  python-version:
    description: "Python version"
    required: false
    default: "3.12"
outputs:
  changed:
    description: "Whether any files were modified by the fixers"
    value: ${{ steps.runfix.outputs.changed }}
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Load tool versions
      shell: bash
      run: |
        cat .github/workflows/autofix-versions.env >> $GITHUB_ENV
    - name: Install fixers
      shell: bash
      run: |
        python -m pip install -U pip
        pip install -e ".[dev]" \
          ruff==${RUFF_VERSION} \
          black==${BLACK_VERSION} \
          isort==${ISORT_VERSION} \
          docformatter==${DOCFORMATTER_VERSION}
    - name: Run fixers
      id: runfix
      shell: bash
      run: |
        ruff check --fix .
        black .
        isort .
        docformatter -r -i src tests || true
        # --- Type hygiene (lightweight) ---
        echo "[autofix] Running auto_type_hygiene..."
        python scripts/auto_type_hygiene.py || true
        echo "[autofix] Installing missing type stubs (non-fatal)..."
        mypy --install-types --non-interactive || true
        # Optional warm cache (do not fail build)
        mypy src/ --ignore-missing-imports --follow-imports=silent > /dev/null 2>&1 || true
        if ! git diff --quiet; then echo "changed=true" >> $GITHUB_OUTPUT; else echo "changed=false" >> $GITHUB_OUTPUT; fi
    - name: Summary
      shell: bash
      run: |
        echo "### Composite Autofix Summary" >> $GITHUB_STEP_SUMMARY
        echo "Changed: ${{ steps.runfix.outputs.changed }}" >> $GITHUB_STEP_SUMMARY