"""LLM utilities for Trend Model."""

from .chain import ConfigPatchChain, ResultSummaryChain, ResultSummaryResponse
from .nl_logging import NLOperationLog
from .prompts import (
    DEFAULT_RESULT_RULES,
    DEFAULT_RESULT_SYSTEM_PROMPT,
    DEFAULT_SAFETY_RULES,
    DEFAULT_SYSTEM_PROMPT,
    SECTION_CONFIG,
    SECTION_RESULT_METRICS,
    SECTION_RESULT_OUTPUT,
    SECTION_RESULT_QUESTIONS,
    SECTION_RESULT_RULES,
    SECTION_RESULT_SYSTEM,
    SECTION_SAFETY,
    SECTION_SCHEMA,
    SECTION_SYSTEM,
    SECTION_USER,
    build_config_patch_prompt,
    build_result_summary_prompt,
    format_config_for_prompt,
)
from .providers import LLMProviderConfig, create_llm
from .replay import ReplayResult, load_nl_log_entry, render_prompt, replay_nl_entry
from .result_metrics import (
    MetricEntry,
    compact_metric_catalog,
    extract_metric_catalog,
    format_metric_catalog,
)
from .result_validation import (
    RESULT_DISCLAIMER,
    ResultClaimIssue,
    append_discrepancy_log,
    detect_result_hallucinations,
    ensure_result_disclaimer,
    postprocess_result_text,
    validate_result_claims,
)

__all__ = [
    "ConfigPatchChain",
    "ResultSummaryChain",
    "ResultSummaryResponse",
    "DEFAULT_RESULT_RULES",
    "DEFAULT_RESULT_SYSTEM_PROMPT",
    "DEFAULT_SAFETY_RULES",
    "DEFAULT_SYSTEM_PROMPT",
    "SECTION_CONFIG",
    "SECTION_RESULT_METRICS",
    "SECTION_RESULT_OUTPUT",
    "SECTION_RESULT_QUESTIONS",
    "SECTION_RESULT_RULES",
    "SECTION_RESULT_SYSTEM",
    "SECTION_SAFETY",
    "SECTION_SCHEMA",
    "SECTION_SYSTEM",
    "SECTION_USER",
    "build_config_patch_prompt",
    "build_result_summary_prompt",
    "format_config_for_prompt",
    "NLOperationLog",
    "ReplayResult",
    "LLMProviderConfig",
    "create_llm",
    "MetricEntry",
    "compact_metric_catalog",
    "extract_metric_catalog",
    "format_metric_catalog",
    "RESULT_DISCLAIMER",
    "ResultClaimIssue",
    "append_discrepancy_log",
    "detect_result_hallucinations",
    "ensure_result_disclaimer",
    "postprocess_result_text",
    "validate_result_claims",
    "load_nl_log_entry",
    "replay_nl_entry",
    "render_prompt",
]
