name: agent readiness (copilot + codex)

on:
  workflow_dispatch:
    inputs:
      agents:
        description: "Comma-separated agent keys to test"
        default: "copilot,codex"
        required: false
      require_all:
        description: "Fail if any requested agent is not assignable (true/false)"
        default: "true"
        required: false
      copilot_logins:
        description: "Candidate GitHub logins for Copilot (comma-separated)"
        default: "copilot,copilot-swe-agent"
        required: false
      codex_logins:
        description: "Candidate GitHub logins for Codex (comma-separated)"
        default: "chatgpt-codex-connector"
        required: false

permissions:
  contents: read
  issues: write

jobs:
  probe:
    uses: ./.github/workflows/reusable/agents.yml
    secrets: inherit
    with:
      operation: agent_readiness
