# .github/workflows/assign-to-copilot.yml
name: Assign issue to Copilot
on:
  issues:
    types: [labeled]
permissions:
  issues: write
jobs:
  assign:
    if: github.event.label.name == 'agent:copilot'
    runs-on: ubuntu-latest
    steps:
      - name: Assign to @copilot (only if not already assigned)
        uses: actions/github-script@v7
        with:
          script: |
            const { issue } = context.payload;
            const assignees = issue.assignees?.map(a => a.login.toLowerCase()) || [];
            if (!assignees.includes('copilot')) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                assignees: ['copilot']
              });
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: 'Assigned to @copilot. The agent will create a branch and open a PR when ready.'
              });
            }
