name: Assign issue to Copilot
on:
  issues:
    types: [opened, labeled]
permissions:
  issues: write
jobs:
  assign:
    if: contains(join(fromJson(toJson(github.event.issue.labels)).*.name, ','), 'agent:copilot')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const issue_number = context.payload.issue.number;
            await github.rest.issues.addAssignees({ owner, repo, issue_number, assignees: ['copilot'] });
            await github.rest.issues.createComment({ owner, repo, issue_number, body: 'Assigning to @copilot. Please pick up this issue.' });
