name: Assign issue to Copilot
on:
  issues:
    types: [labeled]
permissions:
  issues: write
jobs:
  assign:
    if: github.event.label.name == 'agent:copilot'
    runs-on: ubuntu-latest
    steps:
      - name: Assign to @copilot
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              assignees: ['copilot']
            });
