name: Automerge minor changes

on:
  pull_request_target:
    types: [opened, labeled]

permissions:
  pull-requests: write

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'minor')
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-auto-merge@v3
        with:
          merge-method: squash
          pull-request-number: ${{ github.event.pull_request.number }}
