name: auto-approve agent PRs
on:
  pull_request_target:
    types: [opened, labeled, synchronize, ready_for_review]
permissions:
  pull-requests: write
jobs:
  approve:
    if: >
      github.event.pull_request.draft == false &&
      (
        contains(github.event.pull_request.labels.*.name, (vars.AGENT_FROM_LABEL || 'from:copilot')) ||
        contains(github.event.pull_request.labels.*.name, (vars.AGENT_FROM_LABEL_ALT || 'from:codex'))
      ) &&
      contains(github.event.pull_request.labels.*.name, (vars.AUTOMERGE_LABEL || 'automerge')) &&
      contains(github.event.pull_request.labels.*.name, (vars.RISK_LABEL || 'risk:low'))
    runs-on: ubuntu-latest
    steps:
      - name: Check PR file patterns and size
        id: pr-check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            if (!context.payload || !context.payload.pull_request) {
              core.warning('No pull_request in event payload; refusing to auto-approve.');
              return false;
            }
            const pull_number = context.payload.pull_request.number;
            // Get list of files changed in the PR
            // Octokit v17+ uses github.rest.pulls.listFiles; older versions use github.pulls.listFiles.
            // Prefer github.rest.pulls.listFiles, fallback to github.pulls.listFiles for compatibility.
            const listFiles = github?.rest?.pulls?.listFiles
              ? github.rest.pulls.listFiles
              : github?.pulls?.listFiles;
            if (!listFiles) {
              core.warning('Octokit pulls.listFiles API is unavailable on this runner.');
              return false;
            }
            const files = await github.paginate(listFiles, { owner, repo, pull_number });
            // Allow files by simple glob-like patterns
            const patterns = (process.env.APPROVE_PATTERNS || 'src/**,docs/**,tests/**,**/*.md')
              .split(',')
              .map(s => s.trim())
              .filter(Boolean);
            function match(filename) {
              return patterns.some(p => {
                if (p.endsWith('/**')) return filename.startsWith(p.slice(0, -3));
                if (p.startsWith('**/*.')) return filename.endsWith(p.slice(4));
                return filename === p;
              });
            }
            const allowed = files.every(f => match(f.filename));
            // Limit total lines changed
            const cap = Number(process.env.MAX_LINES_CHANGED || '1000');
            const totalChanges = files.reduce((sum, f) => sum + f.changes, 0);
            const sizeOk = totalChanges <= cap;
            // Set output
            return allowed && sizeOk;
        env:
          APPROVE_PATTERNS: ${{ vars.APPROVE_PATTERNS }}
          MAX_LINES_CHANGED: ${{ vars.MAX_LINES_CHANGED }}
      - name: Auto-approve PR
        if: steps.pr-check.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            if (!context.payload || !context.payload.pull_request) {
              core.warning('No pull_request in event payload; skip approval.');
              return;
            }
            const pull_number = context.payload.pull_request.number;
            const createReview = github?.rest?.pulls?.createReview || github?.pulls?.createReview;
            if (!createReview) {
              core.warning('Octokit pulls.createReview API is unavailable on this runner.');
              return;
            }
            await createReview({
              owner,
              repo,
              pull_number,
              event: 'APPROVE',
              body: 'Auto-approving agent PR'
            });
