name: auto-approve agent PRs

# Hardening Note (Issue #1140)
# This workflow intentionally uses pull_request_target with restricted permissions
# and a sparse checkout of ONLY a trusted allowlist file. It does not execute or
# build PR code. Any expansion beyond the allowlist path must be reviewed.
on:
  pull_request_target:
    types: [opened, labeled, synchronize, ready_for_review]
permissions:
  pull-requests: write
jobs:
  approve:
    if: >
      github.event.pull_request.draft == false &&
      (
        contains(github.event.pull_request.labels.*.name, (vars.AGENT_FROM_LABEL || 'from:copilot')) ||
        contains(github.event.pull_request.labels.*.name, (vars.AGENT_FROM_LABEL_ALT || 'from:codex'))
      ) &&
      contains(github.event.pull_request.labels.*.name, (vars.AUTOMERGE_LABEL || 'automerge')) &&
      contains(github.event.pull_request.labels.*.name, (vars.RISK_LABEL || 'risk:low'))
    runs-on: ubuntu-latest
    env:
      TRUSTED_CONFIG_PATHS: |
        .github/autoapprove-allowlist.json
        .github/agent-label-rules.json
    steps:
      - name: Checkout trusted config
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          persist-credentials: false
          fetch-depth: 1
          filter: tree:0
          path: trusted-config
      - name: Configure sparse checkout for trusted files
        run: |
          set -euo pipefail
          readarray -t patterns <<<"${TRUSTED_CONFIG_PATHS}"
          if [ ${#patterns[@]} -eq 0 ]; then
            echo "::error::No trusted config paths configured" >&2
            exit 1
          fi
          git -C trusted-config sparse-checkout set --no-cone "${patterns[@]}"
      - name: Assert sparse checkout scope (Issue #1140)
        run: |
          set -euo pipefail
          python <<'PY'
import os
import sys
from pathlib import Path

allowed = {
    line.strip()
    for line in os.environ.get('TRUSTED_CONFIG_PATHS', '').splitlines()
    if line.strip()
}
if not allowed:
    print('::error::No trusted config paths defined', file=sys.stderr)
    sys.exit(1)

root = Path('trusted-config')
if not root.exists():
    print('::error::trusted-config checkout missing', file=sys.stderr)
    sys.exit(1)

found = set()
for path in root.rglob('*'):
    if not path.is_file():
        continue
    try:
        rel = path.relative_to(root).as_posix()
    except ValueError:
        continue
    if '/.git/' in f'/{rel}/' or rel.startswith('.git/'):
        continue
    found.add(rel)

missing = sorted(allowed - found)
extra = sorted(found - allowed)

if missing:
    print('::error::Missing required trusted config file(s): ' + ', '.join(missing), file=sys.stderr)
if extra:
    print('::error::Unexpected file(s) in trusted config checkout: ' + ', '.join(extra), file=sys.stderr)

if missing or extra:
    sys.exit(1)
PY
      - name: Check PR file patterns and size
        id: pr-check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            function loadAllowlist(filePath) {
              if (!filePath) {
                return {};
              }
              try {
                const data = fs.readFileSync(filePath, 'utf8');
                return JSON.parse(data);
              } catch (error) {
                core.warning(`Failed to read allowlist from ${filePath}: ${error.message}`);
                return {};
              }
            }
            const allowlistPath = process.env.ALLOWLIST_PATH || 'trusted-config/.github/autoapprove-allowlist.json';
            const allowlist = loadAllowlist(allowlistPath);
            const { owner, repo } = context.repo;
            if (!context.payload || !context.payload.pull_request) {
              core.warning('No pull_request in event payload; refusing to auto-approve.');
              return false;
            }
            const pull_number = context.payload.pull_request.number;
            // Get list of files changed in the PR
            // Octokit v17+ uses github.rest.pulls.listFiles; older versions use github.pulls.listFiles.
            // Prefer github.rest.pulls.listFiles, fallback to github.pulls.listFiles for compatibility.
            const listFiles = github?.rest?.pulls?.listFiles
              ? github.rest.pulls.listFiles
              : github?.pulls?.listFiles;
            if (!listFiles) {
              core.warning('Octokit pulls.listFiles API is unavailable on this runner.');
              return false;
            }
            const files = await github.paginate(listFiles, { owner, repo, pull_number });
            // Allow files by simple glob-like patterns
            const fallbackPatterns = Array.isArray(allowlist.patterns)
              ? allowlist.patterns.filter(p => typeof p === 'string')
              : [];
            const patterns = (process.env.APPROVE_PATTERNS || '')
              .split(',')
              .map(s => s.trim())
              .filter(Boolean);
            const effectivePatterns = patterns.length ? patterns : fallbackPatterns;
            if (!effectivePatterns.length) {
              core.warning('No allowlist patterns configured; refusing to auto-approve.');
              return false;
            }
            function match(filename) {
              return effectivePatterns.some(p => {
                if (p.endsWith('/**')) return filename.startsWith(p.slice(0, -3));
                if (p.startsWith('**/*.')) return filename.endsWith(p.slice(4));
                return filename === p;
              });
            }
            const allowed = files.every(f => match(f.filename));
            // Limit total lines changed
            const cap = Number(process.env.MAX_LINES_CHANGED || allowlist.max_lines_changed || '1000');
            const totalChanges = files.reduce((sum, f) => sum + f.changes, 0);
            const sizeOk = totalChanges <= cap;
            // Set output
            return allowed && sizeOk;
        env:
          ALLOWLIST_PATH: trusted-config/.github/autoapprove-allowlist.json
          APPROVE_PATTERNS: ${{ vars.APPROVE_PATTERNS }}
          MAX_LINES_CHANGED: ${{ vars.MAX_LINES_CHANGED }}
      - name: Auto-approve PR
        if: steps.pr-check.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            if (!context.payload || !context.payload.pull_request) {
              core.warning('No pull_request in event payload; skip approval.');
              return;
            }
            const pull_number = context.payload.pull_request.number;
            const createReview = github?.rest?.pulls?.createReview || github?.pulls?.createReview;
            if (!createReview) {
              core.warning('Octokit pulls.createReview API is unavailable on this runner.');
              return;
            }
            await createReview({
              owner,
              repo,
              pull_number,
              event: 'APPROVE',
              body: 'Auto-approving agent PR'
            });
