name: auto-approve agent PRs
on:
  pull_request_target:
    types: [opened, labeled, synchronize, ready_for_review]
permissions:
  pull-requests: write
jobs:
  approve:
    if: >
      github.event.pull_request.draft == false &&
      (
        contains(github.event.pull_request.labels.*.name, 'from:copilot') ||
        contains(github.event.pull_request.labels.*.name, 'from:codex')
      ) &&
      contains(github.event.pull_request.labels.*.name, 'automerge') &&
      contains(github.event.pull_request.labels.*.name, 'risk:low')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.SERVICE_BOT_PAT }}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            await github.pulls.createReview({
              owner,
              repo,
              pull_number,
              event: 'APPROVE',
              body: 'Auto-approving agent PR'
            });
