name: Codex Issue Bridge (label → draft PR + human command)

on:
  issues:
    types: [opened, labeled, reopened]
  workflow_dispatch:
    inputs:
      test_issue:
        description: "Manually test with a specific issue number (optional)"
        required: false
        default: ""
      post_codex_comment:
        description: "Auto-post '@codex start' as the actor (true/false)"
        required: false
        default: "true"
      pr_mode:
        description: "create | invite (invite = human opens the PR)"
        required: false
        default: "create"

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: codex-issue-${{ github.event.issue.number || inputs.test_issue || github.run_id }}
  cancel-in-progress: false

jobs:
  bridge:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.action == 'labeled' &&
        (contains(github.event.label.name, 'agent:codex') || contains(github.event.label.name, 'agents:codex'))) ||
      (github.event.action != 'labeled' &&
        (
          contains(join(github.event.issue.labels.*.name, ' '), 'agent:codex') ||
          contains(join(github.event.issue.labels.*.name, ' '), 'agents:codex')
        ))
    uses: ./.github/workflows/reusable/agents.yml
    secrets: inherit
    with:
      operation: codex_issue_bridge
      test-issue: ${{ inputs.test_issue || '' }}
      post-codex-comment: ${{ inputs.post_codex_comment || '' }}
      pr-mode: ${{ inputs.pr_mode || '' }}
