# .github/workflows/copilot-autofix-on-failure.yml
name: Ask Copilot to fix failing checks
on:
  check_suite:
    types: [completed]
permissions:
  pull-requests: write
  checks: read
  contents: read
jobs:
  ping-copilot:
    if: github.event.check_suite.conclusion == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Find open PR for this head branch
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const suite = context.payload.check_suite;
            const owner = context.repo.owner, repo = context.repo.repo;
            const prs = await github.rest.pulls.list({ owner, repo, state: 'open', head: `${owner}:${suite.head_branch}` });
            core.setOutput('pr', prs.data[0]?.number || '');
      - name: Exit if not Copilot/Codex PR
        if: steps.pr.outputs.pr != ''
        id: guard
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner, repo = context.repo.repo;
            const pr_number = Number('${{ steps.pr.outputs.pr }}');
            const { data: pr } = await github.rest.pulls.get({ owner, repo, pull_number: pr_number });
            const by = (pr.user?.login || '').toLowerCase();
            const labels = pr.labels.map(l => l.name);
            // Accept either labeled PRs or author names that look like agents
            const isAgent = by.includes('copilot') || by.includes('codex') || labels.includes('from:copilot') || labels.includes('from:codex');
            if (!isAgent) core.setFailed('Not an agent PR');
      - name: Summarize failing checks and comment to @copilot
        if: steps.pr.outputs.pr != '' && !cancelled()
        uses: actions/github-script@v7
        with:
          script: |
            const pr_number = Number('${{ steps.pr.outputs.pr }}');
            const owner = context.repo.owner, repo = context.repo.repo;
            const suite = context.payload.check_suite;
            const { data: runs } = await github.rest.checks.listForSuite({ owner, repo, check_suite_id: suite.id });
            const failing = runs.check_runs
              .filter(r => r.conclusion === 'failure')
              .map(r => `- **${r.name}**: ${r.output?.summary || r.output?.title || 'failed'}`)
              .join('\n') || 'Some checks failed. See logs.';
            await github.rest.issues.createComment({ owner, repo, issue_number: pr_number, body: `@copilot please fix the failing checks:\n\n${failing}` });
