name: Dependency Review

on:
  pull_request:
    branches:
      - phase-2-dev
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    name: Review dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Review dependencies
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
