name: quarantine-ttl
on:
  pull_request:
  push:
    branches: [phase-2-dev]
permissions: read-all
jobs:
  ttl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install parser
        run: python -m pip install pyyaml
      - name: Validate TTLs
        run: |
          python - <<'PY'
          import sys, datetime as dt, yaml, pathlib
          p = pathlib.Path("tests/quarantine.yml")
          if not p.exists():
              print("No quarantine.yml; nothing to do."); sys.exit(0)
          data = yaml.safe_load(p.read_text()) or {}
          today = dt.date.today()
          expired = []
          for t in data.get("tests", []):
              if isinstance(t, dict) and "expires" in t:
                  try:
                      if dt.date.fromisoformat(t["expires"]) < today:
                          expired.append(t["id"])
                  except Exception:
                      print(f"Bad date for {t.get('id')}: {t.get('expires')}")
                      expired.append(t.get('id','<unknown>'))
          if expired:
              print("Quarantine entries expired:")
              for e in expired: print("-", e)
              sys.exit(1)
          print("All quarantine TTLs valid.")
          PY
