name: Verify service bot token

on:
  workflow_dispatch:

jobs:
  check-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check if SERVICE_BOT_PAT is set
        run: |
          if [ -z "${{ secrets.SERVICE_BOT_PAT }}" ]; then
            echo 'SERVICE_BOT_PAT is not configured.'
            exit 1
          fi
      - name: Inspect token scopes
        env:
          TOKEN: ${{ secrets.SERVICE_BOT_PAT }}
        run: |
          headers=$(curl -sI -H "Authorization: token ${TOKEN}" https://api.github.com/)
          echo "$headers" | grep -i '^x-oauth-scopes:' || echo 'No scopes header found'
          scopes=$(echo "$headers" | grep -i '^x-oauth-scopes:' | cut -d':' -f2- | tr -d ' \r')
          if [ -z "$scopes" ]; then
            echo 'Token appears invalid or lacks scopes header'
            exit 1
          fi
          echo "Detected scopes: $scopes"
          if ! echo "$scopes" | grep -q 'repo'; then
            echo 'Missing repo scope'
            exit 1
          fi
          if ! echo "$scopes" | grep -q 'workflow'; then
            echo 'Missing workflow scope'
            exit 1
          fi
